### ISSUE TITLE
macOS Ventura 13.3 broke something

### ISSUE THREAD

**Issue by monroewilliams** [monroewilliams/MatrixDownload#11]
After updating from macOS Ventura 13.12.1 to Ventura 13.3, I'm seeing blank screens.

On one machine (Intel MacBook Pro), all screens are blank both when using "Preview" from the Screen Saver panel, and when invoking the screensaver with a hot corner.

On another machine (Mac Studio), behavior is inconsistent -- sometimes it works correctly, other times it renders on only one of the connected displays, or not at all.

The small preview in the System Settings panel *does* render correctly in all cases I've seen.

I don't know what changed yet, but will investigate soon.

**Comment by paulburd** [comment]
Just an FYI.... on my M1 Max 16" MacBook Pro it seems to work consistently, but it only comes up on the built-in display, and not on my external display if I'm using both simultaneously. If I close the laptop and only use the external, it does show on the external as it should.

**Comment by naanoo** [comment]
I can confirm that. Only black blank screens since macOS 13.3 on my Mac Studio.

**Comment by felder** [comment]
Also can confirm that 13.3 broke something.

**Comment by ifixr** [comment]
I've just tried Apple's screen savers and - someof them work on both screens, such as Hello, Ventura, Monterey, Drift, Flurry, Arabesque, Shell, Album Artwork, and, somehow, Word of the Day (didn't it show different definitions on multiple screens?) -

But the others, including Message, and basically all of slideshow ones don't work, although, it is intermittent - during my tests, I saw at least once Floating working, and as well as Origami, although once it was mirroring and another time it was its own.

Wow. I thought about taking screenshot of how the Matrix misbehaves, being not on my MBP screen at all and then taking approx 14 inches on my 27-in 4K display, so I cmd-shift clicked the Preview (thinking of pressing 3 for screenshot) BUT - the Matrix started perfectly on BOTH screens in full size. So the engine works, it's just something is killing transmission 99% of the time.

**Comment by ifixr** [comment]
Intermittent. I've just tried to click the preview button a few times, and it was: three times bad, once good, three times bad, once good, (here I thought I have a pattern but) eight times bad, once good. I wish I could see some logs. But notably - its other screensavers which crash, too. Come on, Apple.

**Comment by irimiab** [comment]
Looks like the "legacy screensavers" are broken after the update. I'm not sure, though, what means to migrate any screensaver to a functional "framework".

It is "reported" here by many users: https://discussions.apple.com/thread/254745941

**Comment by da3x** [comment]
Not sure if it's a pattern... but on my single-screen MacBook Pro (M1 pro) it still works reliably... my multi-screen iMac fails.

**Comment by felder** [comment]
More issue reports here:
https://forums.macrumors.com/threads/multimonitor-screensaver-bug-in-ventura-13-3.2384444/

Along with someone saying that it's supposed to be fixed in 13.4, but others saying the 13.4 betas do not fix.

**Comment by ifixr** [comment]
Looks like 13.4 fixed the issue.

**Comment by naanoo** [comment]
Great! Will install the update and give feedback as well.

**Comment by ifixr** [comment]
Actually. Tried about thirty times with a Hot Corner. About four times, the screen saver didn't start.

Similarly, when I tried one of the built-in savers, such as reflections, it happened occasionally that the both displays showed the same picture (which is, IMHO, the sign of failure).

But - much better to have it 90% working than 10%!

**Comment by felder** [comment]
I upgraded to 13.4 and I see no improvement.  Same behavior as before.  I have 3 screens and nothing shows up on any of them with metal as the chosen renderer.  If I chose opengl one portion of a single screen has it.

The apple provided screen savers such as "Flurry" seem to work ok.

**Comment by akovano** [comment]
I have same issue, using Ventura 13.4 on Macbook Pro with two external monitors. Screensaver only displays on middle screen (which is external monitor, not even on the laptop's built-in display). The MacOS screensavers (Flurry, Drift, Hello, etc) all work as expected and show on all three.

**Comment by jajajaime** [comment]
Same issue here after 13.2.1 --> 13.4 update.

**Comment by tdensmore** [comment]
Mine does display correctly (most of the time) but sometimes renders on the larger monitor with the dimensions of the smaller monitor.

**Comment by ifixr** [comment]
OK, I read the news about 13.5 whilst I was still on 13.4 so I did a test before and after. I normally have a Studio Display connected, but on a work trip now so only testing with a 1080p monitor.

On 13.4, I went to a hot corner to start the screensaver ten times. It failed twice. So failure rate 20%.

On 13.5, I tried about 25× (20× in a row and then about 5× while writing this post) and it hasn't failed once.

I won't jump into conclusions before I try higher-resolution displays as I believe the error is intermittent and can depend on memory usage, but it definitely looks promising.

**Comment by naanoo** [comment]
I just updated my machine to 13.5. Now I am back in the matrix. On all four screens. Without false starts.
![IMG_20230726_112637](https://github.com/monroewilliams/MatrixDownload/assets/16617292/ec8d06c9-9c96-416e-8e29-a7e116f6e7b8)

**Comment by felder** [comment]
I also can confirm that it seems like it works again in 13.5

**Comment by monroewilliams** [comment]
The Ventura 13.5 update also appears to fix the issue for me on two separate machines (Intel and Apple Silicon), so I'm going to call this one resolved.
